config/routes.rb
Rails.application.routes.draw do
  # get 'images/index'
  # get 'images/show'
  # get 'images/new'
  # get 'images/edit'
  # get 'companies/index'
  # get 'companies/show'
  # get 'companies/new'
  # get 'companies/edit'
  resources :cars
  resources :companies
  resources :images
  root "companies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :company
  has_many :images
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :cars
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @info_car = Car.find_by(id: params[:id])
    @image = Car.find_by(id: params[:id]).images
  end

  def new
    @new_car = Car.new
    @styles = ["sport", "sedan", "truck", "luxury"]
    @arr = []
    i = 1996
    while i <= 2018
      @arr.push(i)
      i = i + 1
    end
  end

  def create
    car = Car.create(car_params)
    params[:car][:images].each do |img|
      req = Cloudinary::Uploader.upload(img)
      car.images.create(url: req["url"])
    end
    redirect_to cars_path(car)
  end

  def edit
    @new_car = Car.find_by(id: params[:id])
    @styles = ["sport", "sedan", "truck", "luxury"]
    @arr = []
    i = 1996
    while i <= 2018
      @arr.push(i)
      i = i + 1
    end
  end

  def update
    car = Car.find_by(id: params[:id])
    car.update(car_params)
    redirect_to car_path(car)
  end

  def destroy
    car = Car.find_by(id: params[:id])
    car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:name, :year, :color, :style, :company_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @info_company = Company.find_by(id: params[:id])
    @cars = Company.find_by(id: params[:id]).cars
  end

  def new
    @new_company = Company.new
  end

  def create
    company = Company.create(company_params)
    redirect_to company_path(company)
  end

  def edit
    @new_company = Company.find_by(id: params[:id])
  end

  def update
    company = Company.find_by(id: params[:id])
    company.update(company_params)
    redirect_to company_path(company)
  end

  def destroy
    company = Company.find_by(id: params[:id])
    company.destroy
    redirect_to companies_path
  end

  private

  def company_params
    return params.require(:company).permit(:name, :country)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
  end

  def show
    @image = Image.find_by(id: params[:id])
  end

  def edit
    @image = Image.find_by(id: params[:id])
  end

  def update
    image = Image.find_by(id: params[:id])
    if params[:image]
      req = Cloudinary::Uploader.upload(params[:image][:url])
      image.update(url: req["url"])
      redirect_to car_path(image.car.id)
    else
      redirect_to edit_image_path(image)
    end
  end

  def destroy
    image = Image.find_by(id: params[:id])
    image.destroy
    redirect_to cars_path
  end

  private

  def image_params
    params.require(:image).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/cars/_form.html.erb
<%= form_for @new_car do |f| %>
    <div class="row">
    <div class="col s3">
    <%= f.label  :name %>
    <%= f.text_field :name %>
    </div>
    <div class="col s3">

    <%=  f.label :year %> 
    <%= f.select( :year, @arr) %> 
    </div>

    <div class="col s3">

    <%= f.label :color %>
    <%= f.text_field :color %>
    </div>

    <div class="col s3">

    <%=  f.label :style %> 
    <%= f.select( :style, @styles) %> 
    </div>
    <div class="col s2">

    <%= f.label :company_id %>
    <%= f.collection_select(:company_id,Company.all,:id,:name) %>
    </div>
    <div class="col s2">

    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
    </div>
    <div class="col s2">
    

    <%= f.submit %>
    </div>
    </div>
<% end%>

app/views/cars/edit.html.erb
<%= render partial: "form" %>

app/views/cars/index.html.erb
<h4> All Cars</h4>
<div class="collection">
<ul>
<% @cars.each do |car| %>

 <li><a href="<%= car_path(car) %>" class="collection-item" style="font-size:29px;"><span class="badge" ></span ><%= car.name%></a></li> 
<% end %>

</ul>

</div>

app/views/cars/new.html.erb
<h4> Add new car</h4>
<%= render partial: "form" %>

app/views/cars/show.html.erb
<h4> information about Car</h4>
<div class="row">
<div class="col s3">
<label > name:</label>
<%= @info_car.name %>
</div>

<br>
<label> year:</label>
<%= @info_car.year%>
<br>
<label> color:</label>
<%= @info_car.color %>
<br>
<label> style:</label>
<%= @info_car.style %>
</div>

<br>

<% @info_car.images.each do |img| %>

 <a href=<%= image_path(img) %>>
 <%= image_tag  img.url, :class=>"img"%>
 </a>
 
<% end %>
<br>
<%= link_to "Edit", edit_car_path(@info_car) %>
<%= link_to "delete",car_path(@info_car), method: :delete %>

app/views/companies/_form.html.erb
<%= form_for @new_company do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :country %>
<%= f.text_field :country %>
<%= f.submit %>

<% end %>

app/views/companies/edit.html.erb
<h4>Edit Company</h4>
<%= render  partial:"form"%>

app/views/companies/index.html.erb
<h4>All Companies</h4>





  <div class="collection">
  <ul>
  <% @cars_number = 0 %>
 <% @companies.each do |company| %>
 <% company.cars.each do |car| %>
      <% @cars_number +=1 %>
 <% end%>
   <span class=" new badge " data-badge-caption="Cars "><%= @cars_number %></span>
   <% @cars_number = 0 %>
   <li><a href="<%= company_path(company) %>" class="collection-item" style="font-size:29px;"><span class="badge" ></span ><%= company.name%></a></li> 
  
<%  end%>
    </ul>
  </div>
          

app/views/companies/new.html.erb
<h4> Add new company</h4>
<%= render partial:"form" %>

app/views/companies/show.html.erb
<h4>Information about Company</h4>
<label>Name: </label>
<%= @info_company.name %>
<br>
<label>Country: </label>
<%= @info_company.country %>
<br>
<%= link_to "Edit",edit_company_path(@info_company) %>
<%= link_to "Delete",company_path(@info_company), method: :delete%>
<hr>
<h4>All Cars</h4> 

<div class="collection">
<ul>
<% @cars.each do |car| %>

 <li><a href="<%= car_path(car) %>" class="collection-item" style="font-size:29px;"><span class="badge" ></span ><%= car.name%></a></li> 
<% end %>

</ul>

</div>

app/views/images/edit.html.erb
<h1>Edit Image</h1>
<%= form_for @image do |f| %>
<%=  f.label :url%>
<%= f.file_field :url %>
<%= f.submit %>
<% end %>

app/views/images/index.html.erb
<h1>Images#index</h1>
<p>Find me in app/views/images/index.html.erb</p>

app/views/images/new.html.erb
<h1>Images#new</h1>
<p>Find me in app/views/images/new.html.erb</p>

app/views/images/show.html.erb
<br>
<br>
<div class="container">
     <%= image_tag @image.url,:class=>"imgBig"%>
<br>
<%= link_to "Edit",edit_image_path %>
<%= link_to "Delete",image_path(@image) , method: :delete %>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
  <nav>
  <div class="nav-wrapper blue">
  <ul id="nav-mobile" class="left hide-on-med-and-down ">
          <li><%= link_to "All Companies", companies_path%></li>
          <li><%= link_to "Add Company",new_company_path %></li>
          <li><%= link_to "All Cars", cars_path %></li>
          <li><%= link_to "Add Car", new_car_path,:id=>"newCar" %></li>
  </ul>
  </div>
  </nav>
    <%= yield %>
  </body>
</html>